twig:
    file_name_pattern: "*.twig"
    paths:
        '%kernel.project_dir%/templates': App
    form_themes:
        - 'form/grapesjs_editor_widget.html.twig'

when@dev:
    twig:
        debug: true
        auto_reload: true
        
when@test:
    twig:
        strict_variables: true
